# Generated by Django 4.2 on 2024-02-04 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_time', models.DateTimeField()),
                ('booking_end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='main.stadium')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
