# Generated by Django 4.2 on 2024-02-04 22:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=main.services.upload_logo_path)),
                ('address', models.CharField(db_index=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact1', models.CharField(blank=True, db_index=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid phone number format. It should start with +998 followed by 9 digits.', regex='^\\+998\\d{9}$')])),
                ('contact2', models.CharField(blank=True, db_index=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid phone number format. It should start with +998 followed by 9 digits.', regex='^\\+998\\d{9}$')])),
                ('price', models.PositiveIntegerField()),
                ('start_working_time', models.TimeField()),
                ('end_working_time', models.TimeField()),
                ('lat', models.DecimalField(decimal_places=18, default=0, max_digits=22)),
                ('long', models.DecimalField(decimal_places=18, default=0, max_digits=22)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stadiums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.services.upload_stadium_image)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_stadiums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
