# Generated by Django 4.2 on 2024-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rating_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='long',
            field=models.FloatField(),
        ),
    ]
