# Generated by Django 4.2 on 2024-02-05 12:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stadium_lat_alter_stadium_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
